cli/src/cmd/forge/zk_create.rs

Command:
```
zkforge zk-create src/Counter.sol:Counter --chain 280 --rpc-url https://zksync2-testnet.zksync.dev:443 --private-key "PK"
```
Before:
```
The application panicked (crashed).
Message:  Unable to read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: cli/src/cmd/forge/zk_create.rs:324
```
After:
```
The application panicked (crashed).
Message:  Unable to read contract output file at /onchain/hello-world/zkout/Counter.sol/artifacts.json: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: cli/src/cmd/forge/zk_create.rs:325
```

improve the error message for missing zk compiler output

---

README.md
cli/src/cmd/cast/zk_utils.rs
cli/src/cmd/forge/zksolc.rs
cli/src/cmd/forge/zksolc_manager.rs

zkutils contained an incorrect comment,  zksolc dev comment could use more detail
modified zkutils incorrect comment, and provided more detail to zksolc dev comment

Zkutils comments

---

Cargo.lock

Updated cargo lock - so that we use the zksync era version that has the ssh submodule issue fixed.

updated cargo lock to use the newer version of zksync era

---

Cargo.lock
Cargo.toml
README.md
anvil/Cargo.toml
anvil/core/Cargo.toml
binder/Cargo.toml
cast/Cargo.toml
chisel/Cargo.toml
cli/Cargo.toml
cli/test-utils/Cargo.toml
common/Cargo.toml
config/Cargo.toml
doc/Cargo.toml
evm/Cargo.toml
fmt/Cargo.toml
forge/Cargo.toml
macros/Cargo.toml
ui/Cargo.toml
utils/Cargo.toml

We're currently based off the old fork of foundry, that was depending on the old version of ethers-rs, which supported the solc compiler only up to 0.8.17 (especially on Apple Silicon).
With this PR, I'm moving us to depend on a fork of ethers-rs, that has svm (solidity version manager) patched to the newest release - therefore allowing us to support 0.8.20.
In the near future, we'll rebase ourselves to newer version of foundry, and this dependency would be switched back to original ethers repo.

Added a dependency on ethers-rs fork to support latest solidity

---

README.md
cli/src/cmd/cast/zk_deposit.rs

Fix flags used by zk-deposit:
Use --l1-url and --l2-url (and ignore the --rpc-url flag)

Fix flags for zk deposit

---

Cargo.lock
cli/Cargo.toml
cli/src/cmd/cast/zk_deposit.rs
cli/src/cmd/cast/zk_send.rs
cli/src/cmd/cast/zk_utils.rs
cli/src/cmd/forge/zk_create.rs
cli/src/cmd/forge/zksolc_manager.rs
forge/src/gas_report.rs

`zksync` is a big crate with a lot of functionality that is irrelevant for foundry. That's why we are replacing the crate with the zksync SDK, which provides the same functionality that is needed for foundry but is much more lightweight.
Functionality that has been affected:
- zk_deposit
- zk_send
- zk_create
TODO items to be fully compatible with zksync functionality:
- Deposit and withdrawal of ERC20 tokens (work in progress),

Replace `zksync` crate with `zksync_web3_rs`

---

README.md
crates/zkforge/bin/cmd/test/mod.rs
crates/zkforge/bin/cmd/zk_build.rs
crates/zkforge/bin/cmd/zk_solc.rs

* Resolves import paths issue 
* Having to use relative paths is a pain

fix: resolves import paths issue

---

crates/zkforge/bin/cmd/zksolc_manager.rs

* Adds zksolc 1.3.16
* Removes zksolc 1.3.15
* Latest version of the compiler
* 1.3.15 has been removed

chore: adds latest zksolc compiler

---

Cargo.lock
crates/common/Cargo.toml
crates/common/src/lib.rs
crates/common/src/zk_compile.rs
crates/common/src/zksolc_manager.rs
crates/zkforge/Cargo.toml
crates/zkforge/bin/cmd/mod.rs
crates/zkforge/bin/cmd/test/mod.rs
crates/zkforge/bin/cmd/watch.rs
crates/zkforge/bin/cmd/zk_build.rs
crates/zkforge/bin/main.rs
deny.toml

* moves `zk_solc.rs` and `zksolc_manager.rs` to common crate
* Adds back commented out code
* Removes openssl from `deny.toml`
* This is to follow the existing foundry project structure, specifically the compile operation live in the `common` crate so it can be accessible to other crates. This aligns with `compile.rs` which handles the EVM compilation in common crate.
In addition, this will make adding compile step to `script` subcommand easier.
* Removed `openssl` from `deny.toml` as its a dep of era-test-node currently. Will need to clarify with foundry team why is was added to the ban list. 

chore: moves `zk_solc.rs` and `zksolc_manager.rs` to `common` crate

---

.github/workflows/dependencies.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
crates/anvil/core/Cargo.toml
crates/cheatcodes/Cargo.toml
crates/common/Cargo.toml
crates/common/src/zk_compile.rs
crates/config/Cargo.toml
crates/config/src/lib.rs
crates/debugger/Cargo.toml
crates/evm/Cargo.toml
crates/evm/src/executor/mod.rs
rust-toolchain
rust-toolchain.toml
rust-toolchain.yaml

* Updates revm to latest revision
* Sets env defaults for `env.block.number` and `env.block.timestamp` to `0` as this is what era-test-node starts with
* Fix env update when deploying contracts
* Show solc output when compilation fails
* Required to run `zkforge test`

fix: update revm, fix env update for deployed contracts and era-test-node

---

crates/common/src/zk_compile.rs

Fixed a bug where `zkbuild` would fail once it stumbles on an interface contract
Before:
```bash
RUST_BACKTRACE=1 zz zkbuild --is-system
```
```
...
Compiler run completed with warnings
ApprovalPaymaster -> Bytecode Hash: 01000137af7c45e8c9b466525248692879a3b6d8615affdddebc81f845b73913
GeneralPaymaster -> Bytecode Hash: 010000c96565b4e27d7d6337adc6ecb745ce8100a89d17db7f0627b8d0d7895c
Greeter -> Bytecode Hash: 010000839de6704080006a8df6674d13a03a3fd7fc9631b1f2c4b20e5282a1a0
Compiler run completed with warnings
MyPaymaster -> Bytecode Hash: 01000163ed132df1d2456f946f4410fc38a0cde1609cb222486f7f804e9a7d5d
NFTWalletMultisig -> Bytecode Hash: 010007ef05fda46bbb8dd9c68c5c0b7e3d56dff4637ba9ae5a785f559df943b1
TwoUserMultisig -> Bytecode Hash: …
```

fix: skip contracts with empty bytecode hash to avoid runtime error

---

Cargo.lock
Cargo.toml
crates/common/src/zk_compile.rs
crates/zkforge/bin/cmd/test/mod.rs

* Updates compilers-rs dependency to upstream main
* Makes use of set method for artifact
* Fixes artifacts path to zkout
* No longer need to make use of forked dependency to set artifacts 
* Keeps artifacts path consistent with zkforge zkbuild 

fix: updates compiler dependency to main branch, fixes artifact path

---

crates/common/src/zksolc_manager.rs

**NOTE:** We should update to auto fetch latest compiler version rather then depend on hardcoded values similar to our hardhat plugin. Opened an issue which is considered a good first issue: https://github.com/matter-labs/foundry-zksync/issues/208
* Adds compiler versions 17,18,19
* Sets default to 19
* The compiler versions include changes relevant to compiling improvements and solc support (0.8.23)

feat: adds latest zksolc compiler version

---

crates/common/src/zk_compile.rs
crates/zkforge/bin/cmd/test/mod.rs
crates/zkforge/bin/cmd/zk_build.rs

* Fixes compilation paths issue 
* Compiles all project files in src / tests / scripts. Previously we were only compiling contracts in `/src`. 
* Can successfully compile nested contracts in `/lib` and no longer rely on hacky regex 
* Contracts in scripts and tests were not being correctly compiled 
The one caveat, is now that we are compiling all contract files, in larger projects with 200+ contracts it takes a while to compile. This can be remedied when a long-term refactor of `zk_compile.rs` is done.

fix: addresses compilation paths issue and correctly compiles all project files

---

crates/era-cheatcodes/src/cheatcodes.rs
crates/era-cheatcodes/tests/src/cheatcodes/ExpectCall.t.sol

* Adds `vm.expectCall` cheatcode
* To further support foundry cheatcodes on zksync.

feat: add `vm.expectCall` cheatcode

---

crates/era-cheatcodes/src/cheatcodes.rs
crates/era-cheatcodes/src/utils.rs
crates/era-cheatcodes/tests/src/cheatcodes/Snapshot.t.sol

* Adds `vm.snapshot` and `vm.revertTo` cheatcodes
* To further support foundry cheatcodes on zksync.

feat: add snapshot cheatcodes

---

crates/evm/core/src/era_revm/db.rs

* Improves system context storage retrieval
* Block number and timestamp are being pulled from system context storage, but decoding was done in a wrong way
* In order to prevent future mistakes decoding system context storage
-

fix: improve system context storage retrieval

---

crates/era-cheatcodes/src/cheatcodes.rs
crates/era-cheatcodes/tests/src/cheatcodes/Fork.t.sol

* Active fork cheatcode implementation
* Support foundry cheatcodes
<!-- # Notes :memo:
* Needs to be able to test it

feat: activeFork cheatcode implementation

---

README.md
SUPPORTED_CHEATCODES.md
crates/cli/src/opts/build/mod.rs
crates/config/src/lib.rs
crates/forge/tests/cli/config.rs
crates/zkforge/bin/cmd/test/mod.rs
crates/zkforge/bin/cmd/zk_build.rs
crates/zkforge/tests/cli/config.rs
docs/dev/zksync/zkcast-usage.md
docs/dev/zksync/zkforge-usage.md
docs/dev/zksync/zksync-aa-usage.md

* Resolves an issue where zksolc config options were not being correctly set from .toml file
* Updates readme / docs to reflect current state of project
* Making use of .toml file is easy way to configure project for zksync usage
* Reflects current supported features and limitations and acknowledges the tremendous work provided by @matter-labs/external-moonsonglabs-team 
Can now make use of .toml configuration like so:
```
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
[profile.zksync]
src = 'src'
libs = ['lib']
fallback_oz = true
```
And use it accordingly:
`FOUNDRY_PROFILE=zksync zkforge zkbuild`

fix: resolve issue with setting zksolc configuration values in .toml and update readme / docs

---

.github/workflows/dependencies.yml
.github/workflows/test.yml
crates/common/src/zk_utils/mod.rs
crates/era-cheatcodes/src/cheatcodes.rs
crates/era-cheatcodes/tests/src/cheatcodes/ForkBytecode.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/ForkBytecodeSetup.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/ForkBytecodeSetup2.t.sol
crates/evm/core/src/era_revm/node.rs
crates/evm/core/src/era_revm/transactions.rs
crates/evm/core/src/fork/backend.rs
crates/evm/evm/src/executors/mod.rs
crates/evm/evm/src/inspectors/stack.rs
crates/zkforge/bin/cmd/zk_create.rs
rust-toolchain

* persists bytecodes on fork
* Required to deploy contract in stages other than `setUp` after a fork.
Tests pass
* Supersedes https://github.com/matter-labs/foundry-zksync/pull/230
* Still need to fix a edge case

fix: persist bytecodes on fork

---

crates/era-cheatcodes/src/cheatcodes.rs
crates/era-cheatcodes/tests/src/cheatcodes/ExpectEmit.t.sol

* Fix the compare logs function to be correct according to [Foundry documentation](https://book.getfoundry.sh/cheatcodes/expect-emit)
* In the past implementation if a given log A was expected but was not the first one found in the actual logs it would fail. This is not how the documentation presents the use case. It should need the right order of expected logs but there could be new ones after, before or in the middle of that expected logs.

fix: Log matching

---

.gitmodules
crates/common/src/zk_utils/mod.rs
crates/era-cheatcodes/src/cheatcodes.rs
crates/evm/core/src/era_revm/transactions.rs
smoke-test/.gitignore
smoke-test/script/Counter.s.sol
smoke-test/script/NFT.s.sol
smoke-test/src/Counter.sol
smoke-test/src/NFT.sol
smoke-test/test.sh

* This would earlier fail as the factory deps would not be added if the contract was already deployed on chain (since it would never return it in the changeset from the VM)
* Adds scripting functionality to smoke tests
* Adds `is Test` to Counter script since `setUp` calls within scripts call `failed()` which is defined on `DSTest`.
* Repeated deploys must not fail
* Added smoke tests to prevent regressions
Tests pass
* Using a different variation of Counter contract for script as adding `setNumber` causes certain cases of invariant testing to fail in the original contract (as expected)

fix: zkforge script repeated deploys

---

crates/zkforge/bin/cmd/script/build.rs
crates/zkforge/bin/cmd/script/cmd.rs

* Fixes path detection for running scripts with forge. The `script` folder was only being checked, while the `scripts` folder was missing.
* Failing script running with forge

fix: improve script path detection

---

Cargo.lock
SUPPORTED_CHEATCODES.md
crates/era-cheatcodes/Cargo.toml
crates/era-cheatcodes/src/cheatcodes.rs
crates/era-cheatcodes/tests/src/cheatcodes/Env.t.sol

* Add env cheatcodes:
*  `envOr`
* `envBool`
* `envInt`
* `envAddress`
* `envBytes32`
* `envString`
* `envBytes`
* Remove unused dependencies
* Reorganize to use workspace dependencies
* Further support Foundry

feat: add env cheatcodes

---

crates/zkcast/bin/main.rs
crates/zkcast/bin/opts.rs

* add back removed zksync zkcast subcommands `zk-send`, and `zk-deposit` 
* These commands enable L2 → L1 Withdrawals and L1 → L2 Deposits
* Looks like these were removed during the previous rebase

fix: add back removed zksync zkcast subcommands

---

.github/workflows/test.yml
crates/era-cheatcodes/tests/foundry.toml
crates/era-cheatcodes/tests/src/cheatcodes/Fork.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/ForkBytecode.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/ForkBytecodeSetup.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/ForkBytecodeSetup2.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/ForkStorage.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/Persistent.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/RollFork.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/RpcUrls.t.sol
crates/era-cheatcodes/tests/src/cheatcodes/Transact.t.sol
crates/era-cheatcodes/tests/test.sh

* Update cheatcodes-test CI to use local era-test-node
* To fix rate limit issue caused when executing cheatcodes-test CI due to rate limiting by mainnet RPC
CI run.

feat: update cheatcodes-test CI to use local era-test-node

---

crates/cheatcodes/src/inspector.rs
crates/cheatcodes/src/script.rs
crates/cheatcodes/src/utils.rs
crates/common/src/zksolc_manager.rs
crates/config/src/lib.rs
crates/config/src/zksolc_config.rs
crates/era-cheatcodes/src/cheatcodes.rs
crates/era-cheatcodes/tests/src/cheatcodes/Roll.t.sol
crates/evm/evm/src/executors/mod.rs
crates/evm/evm/src/inspectors/stack.rs
crates/zkforge/bin/cmd/script/executor.rs
crates/zkforge/bin/cmd/script/runner.rs
crates/zkforge/bin/cmd/test/mod.rs

* Fixes script broadcast deployment when using a private key
* Upgrades zksolc to v.1.4.0
* Disables request memoization (zksolc >= v.1.3.3) which allows for modifying system contracts storage on foundry tests
* Fix #261
* Fix era-cheatcodes tests failing

fix: script broadcast error and request memoization on zksolc

---

.github/workflows/test.yml

* always upload era-test-node logs in ci
* The logs are especially important when cheatcode test failurer occur.
-

chore: always upload era-test-node logs in ci

---

Cargo.lock
crates/common/src/zk_compile.rs
crates/forge/Cargo.toml
crates/zkforge/Cargo.toml
crates/zkforge/bin/cmd/zk_build.rs

* Update `svm` crate version `v0.3.0` -> `v0.3.5`.
* Add error handling to the `zkbuild` command of the zkforge.
* To support the `solc` `^0.8.21`. You can check the previous list of supported versions [here](https://raw.githubusercontent.com/alloy-rs/solc-builds/55ef6c89b8a09c16feee4a424f8a53f822831a61/macosx/aarch64/list.json) (it is specific for macOs and aarch, but for other variations of OSs and ARCHs the max version is the same). And [here](https://raw.githubusercontent.com/alloy-rs/solc-builds/e4b80d33bc4d015b2fc3583e217fbf248b2014e1/macosx/aarch64/list.json) is the updated one.
* To improve the user experience. Otherwise, it ignores errors and makes debugging impossible.
* Fixes #272
* Fixes #276

fix: bump svm version to `v0.3.5`

---

Cargo.lock
crates/cheatcodes/src/inspector.rs
crates/evm/evm/src/executors/mod.rs
crates/zksync/compiler/Cargo.toml
crates/zksync/compiler/src/zksolc/config.rs
crates/zksync/core/src/lib.rs
crates/zksync/core/src/state.rs
crates/zksync/core/src/vm/db.rs
crates/zksync/core/src/vm/runner.rs
zk-tests/test.sh

* Transaction failures due to duplicate (deployment) nonces
* Multiple deployments of the same contract do not return the bytecode for subsequent deployments, and as such the new address (from second deployment onwards) does not have a valid bytecode causing failures.
* Deployment nonces are handled internally, and as such only transaction nonces must be used for both `CALL` and `CREATE`
* For all non-system addresses, the bytecode is fetched via rpc and stored in the foundry account info.
smoke test passes

fix: use tx_nonce for transactions, handle multiple deploys for same bytecode

---

README.md
foundryup-zksync/foundryup-zksync
foundryup-zksync/install

- Having the binaries installed in the same location as upstream allows binary installation to be overridden removing the issues of multiple forge versions
- Adds note in readme outlining this behaviour

chore: update binary location in installation scripts

---

crates/zksync/core/src/vm/runner.rs
crates/zksync/core/src/vm/tracer.rs
zk-tests/src/Basic.t.sol

CrossChainReceiverTest currently has 4 failing tests.
The assertions that are failing are all related to `block.timestamp` being different than expected, this is because each zk call happens in a new transaction in a new batch, and all batches need to have increasing numbers and timestamps.
We override what the VM returns for `block.timestamp` and `block.number` so we can provide the expected test environment.
Depends on https://github.com/Moonsong-Labs/aave-delivery-infrastructure/pull/3

fix: Propagate block environment to zkVM

---

Cargo.lock
Cargo.toml
crates/zksync/core/src/vm/farcall.rs
crates/zksync/core/src/vm/runner.rs
crates/zksync/core/src/vm/tracer.rs
zk-tests/src/Cheatcodes.t.sol
zk-tests/test.sh

Current mocked payable functions panic when a mocked return is triggered.
After careful investigation of the `FARCALL` and `RET` opcodes and the `era-zk_evm`. Certain differences were observed owing to the role `MsgValueSimulator` contract plays causing differences in the `base_memory_page` used for returning data and the propagation of `is_local_frame`, which doesn't work for normal farcalls. 
This scenario is currently not well understood as it's quite primitive in nature, and may need to be fixed again in future as different edge cases arise.
`zksync-era` deps were updated as debugging was not possible anymore with older pinned hashes for many of the transitive deps.

fix: mocked return from payable functions

---

crates/zksync/core/src/vm/runner.rs
crates/zksync/core/src/vm/tracer.rs
zk-tests/src/Contracts.t.sol

Previously all calls to `SYSTEM_DEPLOYER` contract were being treated as create calls, and being decoded as such, which resulted in failures.
Demarcate calls explicitly as create calls, instead of assuming all calls to `SYSTEM_DEPLOYER` are create.

fix: specify create calls explicitly

---

crates/cheatcodes/src/evm/mock.rs
crates/cheatcodes/src/inspector.rs
crates/zksync/core/src/cheatcodes.rs
crates/zksync/core/src/lib.rs

Accounts with empty bytecode (`0x0`) could not be translated to zk-vm as the corresponding `DualCompiledContract` is not available. This causes cheatcode address to not work correctly when switching VMs.
Adds a manual `DualCompiledContract` entry for the empty bytecode (`0x0`), with its corresponding valid zk-vm bytecode.
Makes the following tetsts pass https://github.com/Moonsong-Labs/aave-delivery-infrastructure/pull/14

fix: allow switching accounts with empty bytecode to zk vm

---

.github/workflows/infrastructure.yml

Currently we are running the aave delivery infrastructure tests on the same branch that we'll propose the BGD team to merge. This branch has a few tests that fail, which we'd like to keep separate from the CI from the time being.
A specific `ci` branch has been made on the test repo, so we use that one instead

fix: switch to `ci` branch on test repo

---

crates/cheatcodes/src/evm/mock.rs
crates/zksync/core/src/cheatcodes.rs
zk-tests/src/Cheatcodes.t.sol

Our current implementation of zkVM doesn't allow us to make calls to the `tx.origin` address.
Add a test to document this limitation, and add an error log when mocking the `tx.origin` address, assuming that the intention is for that address to be called.

docs: log error if trying to mock `tx.origin`

---

crates/cheatcodes/src/inspector.rs
crates/evm/core/src/backend/fuzz.rs
crates/evm/core/src/backend/mod.rs
zk-tests/src/SetupForkFailure.t.sol

During forking during `setUp` when run with `--zksync`, the test contract isn't in the `persisted_accounts` list during initialization and as such isn't migrated to zksync. This causes it to be incorrectly migrated to an empty code account when a evm fork is encountered.
This in turn causes the test to _silently pass_ as it's never called (since we've effectively erased the test contract). Such a failure can be detected by a negative test, which foundry provides via `testFail`, i.e. if the function doesn't revert the test fails -ensuring that the test is executed.
Avoid migrating test contract at all, since we never call it in zksync context.
An alternate solution would be to detect if the test contract is in `persisted_accounts` and has not been migrated yet, to selectively migrate it to …

fix: avoid test contract migration

---

crates/forge/bin/cmd/create.rs
crates/zksync/compiler/src/lib.rs
crates/zksync/compiler/src/libraries.rs
crates/zksync/compiler/src/zksolc/compile.rs

With #357 we added support to `forge create` to deploy missing libraries found from a previous compilation.
We correctly sequence the libraries to be deployed in order, but as we compile all libraries together, we would find that nested libraried needed to be deployed, necessitating us to restart the cycle.
We organize the libraries in batches, where batch n+1 has dependencies in batch n. 
By compiling and deploying each batch in sequence, we are able to deploy all libraries in the same invocation.
This PR also brings some refactors to the compilation process:
* `--detect-missing-libraries` flag is not passed to the compiler unless compilation fails and it's detected to be due to missing libraries
* sources filtering happens ahead of time, skipping ignored files and providing slightly …

fix: support deploying nested lib directly in create

---

zk-tests/src/Cheatcodes.t.sol

The current fuzz test to assert special addresses can be mocked fails if the input address is the next create address. This is not a failure in mocking the call but rather the contract cannot deploy as the `mockCall` inserts an empty bytecode in it for mocking purposes.
Deploy the contract before mocking, to avoid the empty bytecode insertion.

fix: fuzz test failure on create address

---

README.md
crates/zksync/core/src/vm/runner.rs

Resolve hashes functionality for the zkEVM output was always enabled owing to introduction of a new `show_output` parameter.
Handle `resolve_hashes` and `show_output` correctly based on environment variables. Update README.

fix: resolve hashes always enabled

---

.github/workflows/release.yml
crates/zksync/core/src/cheatcodes.rs
crates/zksync/core/src/vm/db.rs
crates/zksync/core/src/vm/runner.rs
zk-tests/src/Contracts.t.sol

The storage was being read from journaled accounts directly. `load_account` does not populate the storage and thus storage needs to be read via `sload`. This would cause issues in mocking contracts deployed during setup (as the journaled state would be empty, triggering this behavior).
Correctly read from journaled state, instead of reading from partially loaded account.
Storage writes can still be performed on loaded accounts.

fix: use journaled state to read storage

---

crates/cheatcodes/src/inspector.rs
crates/zksync/core/src/vm/runner.rs

During tests or scripts execution, logs that happen inside of the zk VM are collected and returned once a given call has succeeded.
This makes it particularly hard to debug reverts and similar failures, where the logs are not retrieved and thus are not able to be displayed to the user.
This makes use cases such as print debugging via `console.log` useless, as it becomes impossible to bisect a function execution thru it.
Logs are stored separtely from the execution result of the zkVM, thus they can be retrieved even during reverts or panics.
The `revm::ExecutionResult` type only stores logs when execution succeeds, therefore it's necessary to store the logs alongside it (and not inside) if we want to be able to retrieve them for all executions.

feat: always get logs after zkvm execution

---

crates/cheatcodes/src/inspector.rs
zk-tests/src/Contracts.t.sol

When an account balance is read, and zk mode is enabled, we intercept the `BALANCE` opcode and read the balance from the L2 Eth system contract.
When checking the test address's balance (via `address(this).balance`), any balance change seems to not be reflected, causing failures on some [tests](https://github.com/bgd-labs/aave-governance-v3/blob/0c14d60ac89d7a9f79d0a1f77de5c99c3ba1201f/tests/GovernanceCore.t.sol#L854).
`address(this).balance` doesn't always use the `BALANCE` opcode, but the `SELFBALANCE` opcode instead (or at least, it _can_ use that opcode), as it is more gas efficient.
Adding support for this opcode ensures that this pattern reads the expected contract balance.

fix: add support for SELFBALANCE opcode

---

README.md

There are many issues reported that are due to using incompatible `zksolc` and `solc` versions.
Add a note in limitations section about `zksolc`/`solc` compatibility. Long term solution might be enforcing compatibility automatically either downloading and using the binaries automatically and/or failing with a clear error message when incompatibility is detected due to versions derived from config.

docs: add notes solc version compatibility with zksolc

---

crates/zksync/core/src/vm/db.rs
crates/zksync/core/src/vm/runner.rs
zk-tests/src/Basic.t.sol
zk-tests/test.sh

ChainId was not being respected when system contracts were being created, leading to an inconsistency if tests were run with a custom `--chain`.
* Consistently handle the passed in chainId.
* Run tests with `--chain` to catch this case.
Fixes #390

fix: use consistent chainId in zkEVM

---

crates/cheatcodes/src/inspector.rs
zk-tests/src/Cheatcodes.t.sol

The logs emitted in a create function are not going through the logic to handle the expected emits. 
Replicate the way to handle expect emits from call to create function

fix: Add handle expect emit on create

---

Cargo.lock
README.md
crates/cli/src/opts/build/mod.rs
crates/config/src/lib.rs
crates/forge/tests/cli/config.rs

[This PR ](https://github.com/Moonsong-Labs/compilers/pull/4) in zksync's fork of foundry compilers adds a new setting for zksolc's `--solc` option.
Add `zk_solc_path` config value that allows the user to set the option

feat: add zk-solc-path option

---

crates/cli/src/opts/build/core.rs
crates/cli/src/opts/build/mod.rs
crates/cli/src/opts/build/zksync.rs
crates/config/src/lib.rs
crates/config/src/zksync.rs
crates/forge/bin/cmd/build.rs
crates/forge/bin/cmd/create.rs
crates/forge/bin/cmd/script/executor.rs
crates/forge/bin/cmd/test/mod.rs
crates/forge/tests/cli/config.rs

All zksync related configurations are flattened into the top level `Config` struct, having to deal with duplicated names and need to keep relatively simplified values to encode wanted behavior.
Encapsulate zksync related configuration as to not pollute the top level `Config` struct, allowing a more structured approach to configuration.
This is how `foundry.toml` _can_ look like, with the changes:
```
[zksync] #all configuration below lives inside the `zksync` item
enable = false # can still be enabled from the cli
zksolc = "1.5.0"
force_evmla = true
fallback_oz = true
solc_path = "./solc-0.8.23-1.0.1"
optimizer = true
optimizer_mode = 'z'
```
before:
```
zksync = true
zksolc = "1.5.0"
force_evmla = true
fallback_oz = true
zk_solc_path = "./solc-0.8.23-1.0.1"
zk_optimizer = true
mode = 'z' …
```

refactor(config): split zk-related configuration

---

crates/forge/bin/cmd/create.rs

In an [issue's comment](https://github.com/matter-labs/foundry-zksync/issues/434#issuecomment-2181219499) it was outlined that when creating a contract that expects arguments but none were passed a non-helpful error is thrown.
>Seems like the error code is wrong. It should say like "forgot constructor arguments."
Add a warning when the number of constructor arguments passed doesn't match the expected inputs indicated by the contract's ABI.
This PR also changes the CLI for `create` in 2 ways:
* error if both `--constructor-args` and `--constructor-args-path` are specified, as only the latter would be used
* error if both `--deploy-missing-libraries` and a target contract are specified, as only the former would be used

feat(create): empty constructor args warning

---

Cargo.lock
Cargo.toml
crates/forge/bin/cmd/create.rs
crates/forge/bin/cmd/script/verify.rs
crates/forge/bin/cmd/verify/etherscan/flatten.rs
crates/forge/bin/cmd/verify/etherscan/mod.rs
crates/forge/bin/cmd/verify/etherscan/standard_json.rs
crates/forge/bin/cmd/verify/mod.rs
zk-tests/foundry.toml

Closes #102 
We need to add 2 fields to the Etherscan request to make it compatible with their API for ZkSync:
* `compilermode` to indicate wheter to use `zksync-solc` or just `solc` with `zksolc`
* `zksolcVersion` to indicate the version of `zksolc` in use
We also have to provide the zksolc settings instead of the solc ones.
~~### Warning
The current version of the branch most likely breaks compatibility with Etherscan, instead focusing on https://explorer.zksync.io compatibility.
Please use the API endpoints listed [in the docs](https://docs.zksync.io/build/tooling/zksync-block-explorers#block-explorer-api). An API key is **_not_** required by these endpoints, but `forge` still requires the value to be present, which can be anything.~~

feat(verify): zksync contract verification

---

crates/cheatcodes/src/inspector.rs
crates/evm/core/src/backend/fuzz.rs
crates/evm/core/src/backend/mod.rs
crates/evm/evm/src/executors/mod.rs
crates/forge/bin/cmd/script/broadcast.rs
crates/forge/bin/cmd/script/executor.rs
crates/zksync/core/src/cheatcodes.rs
crates/zksync/core/src/lib.rs
crates/zksync/core/src/vm/inspect.rs
crates/zksync/core/src/vm/mod.rs
crates/zksync/core/src/vm/runner.rs
crates/zksync/core/src/vm/tracer.rs
zk-tests/script/Deploy.s.sol
zk-tests/src/Contracts.t.sol
zk-tests/src/Greeter.sol
zk-tests/src/LargeFactoryDependencies.t.sol
zk-tests/test.sh

Batching factory deps has been added since #412, but support for broadcastable tx (and create) was never done.
After investigating #450 it became clear that the simulation issue was due to this missing feature.
1. Batch factory deps in broadcastable txns, creating new transactions as needed
2. Add support for `persisted_factory_deps` for `transact`, used in simulation

fix: batch factory deps for broadcastable tx

---

Cargo.lock
crates/evm/evm/src/executors/mod.rs
crates/script/Cargo.toml
crates/script/src/broadcast.rs
crates/script/src/build.rs
crates/script/src/execute.rs
crates/script/src/lib.rs
crates/script/src/receipts.rs
crates/script/src/simulate.rs
crates/zksync/core/Cargo.toml
crates/zksync/core/src/convert.rs
crates/zksync/core/src/convert/eip712.rs

Forward-port scripting changes to `foundry-update-4af6cfa`.
Added a few more conversion for types as more things have been moved to alloy.
Tested slightly locally but `--broadcast` fails with `era-test-node`

fix: script [upstream merge]

---

crates/cheatcodes/src/inspector.rs
crates/evm/core/src/backend/cow.rs
crates/evm/core/src/backend/mod.rs
crates/evm/evm/src/executors/mod.rs
crates/zksync/core/src/cheatcodes.rs
crates/zksync/core/src/lib.rs
crates/zksync/core/src/vm/inspect.rs
crates/zksync/core/src/vm/mod.rs
crates/zksync/core/src/vm/runner.rs
crates/zksync/core/src/vm/tracer.rs
zk-tests/script/Deploy.s.sol
zk-tests/src/Contracts.t.sol
zk-tests/src/Greeter.sol
zk-tests/src/LargeFactoryDependencies.t.sol
zk-tests/test.sh

Forward port #455 to `foundry-update-4af6cfaq`.
Also added `inspect_ref_zk` for `call_with_env`, used in scripting's simulations.

fix: batch broadcastable factory deps [upstream merge]

---

crates/config/src/lib.rs

Default `evm_version` on `Config` was being hardcoded to `Paris` even though the default value was `Cancun`
Use `Default::default()` to set `evm_version` so we keep up to date with whatever version is set upstream.

feat: use default EvmVersion on default Config

---

crates/forge/bin/cmd/create.rs

`forge create ` on zksync mode was compiling the whole project instead of target to be deployed 
Only compile target to deploy

fix: only compile target file on create

---

crates/zksync/core/src/vm/runner.rs
crates/zksync/core/src/vm/tracer.rs
zk-tests/src/Basic.t.sol

Blockhash of current block should be zero not yield a value
Respect the L1 behaviour from the Cheatcode Tracer

fix: Blockhash of current block should be zero

---

README.md
crates/common/src/compile.rs

While we removed `--deploy-missing-libraries` feature, there were still some error messages and docs mentioning it.
Replace mentions with messages that reflect current state of the missing libraries flow.

chore: remove deploy missing libraries mentions

---

crates/script/src/broadcast.rs

Broadcast would fail if simulation was skipped as `factory_deps` weren't being provided.
Add factory deps while estimating gas.

fix: add factory_deps to estimate_gas

---

crates/cheatcodes/src/inspector.rs
crates/zksync/core/src/vm/farcall.rs
crates/zksync/core/src/vm/inspect.rs
crates/zksync/core/src/vm/runner.rs
crates/zksync/core/src/vm/tracer.rs

We had added a `Send` bound to the `DB` for Cheatcodes, but it doesn't seem to be used anywhere, and this makes merging with upstream more difficult.
Remove excess `Send`.

fix: remove unused `Send` bound on `DB`

---

crates/config/src/lib.rs

We are doing zksolc setup in the multicompiler project, although we are using a separate project now, creating duplicate logic and installing zksolc when not needed.
Remove logic from `Config::create_project()`

chore: do not setup zksolc in multicompiler project

---

crates/cheatcodes/src/inspector.rs
crates/evm/core/src/backend/fork_type.rs
crates/evm/core/src/backend/mod.rs
crates/forge/tests/it/zk/issues.rs
crates/forge/tests/it/zk/mod.rs
crates/zksync/core/src/lib.rs
crates/zksync/core/src/vm/storage_view.rs
testdata/zk/Issues.t.sol
zk-tests/src/Basic.t.sol
zk-tests/src/Issues.t.sol

After #497 report, investigation led to find that the cause was the incorrectly read value from ZK storage, done when migrating back to EVM, which lead to the checks inserted by solidity to fail.
Also migrate account code storage & nonce when switching between ZK forks

fix(zk): merge code storage & nonce with zk-zk

---

Cargo.lock
crates/common/src/compile.rs
crates/forge/bin/cmd/build.rs
crates/forge/tests/cli/build.rs
crates/forge/tests/cli/script.rs
crates/forge/tests/cli/zksync_node.rs

As reported in #504 we are still reporting the size margins from [eip-170](https://eips.ethereum.org/EIPS/eip-170) (foundry default) in zksync mode.
Report margins via zksync's contract sizes as stated in their [documentation](https://docs.zksync.io/build/developer-reference/ethereum-differences/contract-deployment#contract-size-limit-and-format-of-bytecode-hash).

fix: use zksync contract size limits in --zksync mode

---

crates/forge/tests/cli/build.rs

When updating foundry I got some different amount of whitespace on the sizes test table. Whitespace on table alignment may not be consistent.
Use a regex as we care about the having the correct values in the table entry vs having the exact output.

test: use a regex to match build sizes output

---

crates/forge/tests/it/zk/cheats.rs
testdata/zk/MockedModifier.t.sol

Currently we only ensure we can mock calls in modifiers in zk-tests
Migrate test to forge test suite

test(zk): migrate mocked modifier

---

deny.toml

`cargo deny` is failing due to [an issue in sqlx](https://github.com/launchbadge/sqlx/issues/3440) which may potentially cause sql injection involving large user inputs. The issue has not been fixed yet, and the maintainers claim it might not be problematic save for some edge cases. Furthermore, the package is used by `era_test_node`,  where sql injection would not matter as it runs on the user's machine.
Ignore the issue on `cargo deny`

chore: add sqlx issue to cargo deny

---

crates/forge/tests/it/zk/cheats.rs
testdata/zk/Cheatcodes.t.sol

Cheatcodes are not supported in zkVm, but there are no tests that display this limitation
Provide a test case which shows this limitation and also potential pattern to avoid a given contract from being executed in zkVm and thus circumvent this limtation

test(zk): cheatcode usage in zkVm

---

Cargo.lock
crates/cheatcodes/src/inspector.rs
crates/config/README.md
crates/evm/evm/Cargo.toml
crates/evm/evm/src/executors/mod.rs

Reduce custom code for appending zkEVM logs 
Remove `combined_logs` workaround and use `InspectorExt` trait instead.

chore: use InspectorExt trait for logs

---

crates/zksync/compiler/src/lib.rs

`foundry-compilers` api refactor brought a regression regarding using zkvm solc when a solc requirement is specified as logic was lost in the new way to do compiler resolution.
Use dedicated method with zk specific solc resolution for determining how to assign ZkSolcCompiler's `solc` field.
This regression highlights the need to address the following in future PRs:
* Have a way to identify if we will use zkvm or vanilla solc through the whole compilation flow (from logging to sending the info in verify and storing it on `build_info`)
* Have proper integration test to make sure user settings are honored and the correct compiler is being used to compile.

fix: bring back zkvm solc resolution from settings

---

Cargo.lock
crates/config/src/zksync.rs
crates/verify/src/etherscan/flatten.rs

Foundry compilers now uses the ZkSettings and ZkSolcSettings as original Foundry does so we need to adapt to that change
This would solve the [issue](https://github.com/matter-labs/foundry-zksync/issues/411) regarding `allow_paths` not reaching ZK compilation process.

fix: Update dependency foundry compilers use of ZksolcSettings

---

crates/cheatcodes/src/inspector.rs
crates/forge/tests/it/zk/cheats.rs
testdata/zk/Cheatcodes.t.sol

After investigating #546 we noticed that logs were being processed also for `STATICCALL`, which aren't supposed to edit the state.
Logs are part of the state, so we should ignore observing them for `STATICCALL`

fix(zk): avoid observing log from staticcalls

---

crates/cheatcodes/src/inspector.rs
crates/evm/core/src/lib.rs
crates/evm/evm/src/inspectors/mod.rs
crates/evm/evm/src/inspectors/stack.rs
crates/evm/evm/src/inspectors/trace.rs
crates/forge/tests/cli/ext_integration.rs
crates/forge/tests/it/zk/logs.rs
crates/forge/tests/it/zk/mod.rs
crates/forge/tests/it/zk/traces.rs
crates/zksync/core/src/lib.rs
crates/zksync/core/src/vm/inspect.rs
testdata/zk/Console.t.sol
testdata/zk/Trace.t.sol

Attach zkEVM execution traces to foundry traces
Implement custom login in `InspectorExt`
This PR also fixes the following bugs that were discovered:
* `CREATE` was not triggering the inspector stack executor
* ~Gas used was being reported incorrectly from the zkEVM output~ This causes `test_zk_aave_di` to fail with OutOfGas, and as such must be investigated further

feat: add inner zk traces, fix create not registering logs

---

crates/forge/tests/it/test_helpers.rs
crates/forge/tests/it/zk/create.rs

We have a test casting a transaction between two contracts in zk-tests
Migrated the cast test and refactored the forge create tests with a new helper function to avoid duplicated code

test: add cast test to forge create test suite

---

Cargo.lock
deny.toml

ID: RUSTSEC-2024-0370
Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0370
proc-macro-error's maintainer seems to be unreachable, with no commits for 2 years, no releases pushed for 4 years, and no activity on the GitLab repo or response to email.
ID: RUSTSEC-2024-0367
Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0367
`gix-path` executes `git` to find the path of a configuration file that belongs to the `git` installation itself, but mistakenly treats the local repository's configuration as system-wide if no higher scope
d configuration is found. In rare cases, this causes a less trusted repository to be treated as more trusted, or leaks sensitive information from one repository to another, such as sending credentials to another
repository's remote.
* RUSTSEC-2024-0370: …

chore: deal with proc_macro_error and gix_path cargo deny advisories

---

.github/workflows/test.yml
README.md
foundryup-zksync/foundryup-zksync
foundryup-zksync/install
install-foundry-zksync

- Currently quick installation requires cloning the repo locally which all we really need is the `forge` and `cast` binaries. 
- Updates installation scripts to pull and execute script from GH instead.

feat: update installation scripts for quick install

---

.github/workflows/test.yml

CI breaks currently as `foundryzksync-up` tries to install the script within the checked out source which already has a directory by that name.
Perform the install operation in /tmp directory.

fix: install foundryzksync-up in /tmp to prevent conflict with source directory

---

crates/forge/src/multi_runner.rs

In zksync context, the traces cannot decode contracts via EVM bytecode as we only pass zksolc artifacts to `known_contracts`.
```bash
Traces:
[1120167] 0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496::testFoo()
├─ [0] VM::zkVmSkip()
│   └─ ← [Return] 
```
Additionally, invariant tests do not work with `testContract` as during the test, they perform the lookup on the target address and try to match it with a known contract to obtain the ABI for invariant testing. This being an EVM bytecode, the test always fails as we do not know of any solc artifacts within `known_contracts`.
Append solc artifacts to `known_contracts`. This is supported by the argument that in zksync context we are always aware of solc artifacts as we use them to translate bytecodes between VMs. 
This therefore fixes the …

fix: add solc artifacts to known contracts for traces

---

crates/zksync/core/src/vm/runner.rs

Fetching last 256 blocks from rpc causes too much noise, in addition to, several rpc requests.
Make this parameter configurable with the env variable `ZK_DEBUG_HISTORICAL_BLOCK_HASHES`, in the absence of a generic config setting.
```bash
ZK_DEBUG_HISTORICAL_BLOCK_HASHES=0 forge test     # disables fetching historical block hashes
```

chore: take historical block count from env

---

Cargo.lock
crates/cheatcodes/src/inspector.rs
crates/evm/evm/src/inspectors/trace.rs
crates/forge/Cargo.toml
crates/forge/tests/it/zk/traces.rs
crates/zksync/core/src/vm/inspect.rs
crates/zksync/core/src/vm/runner.rs

Unlike EVM, `CREATE` call traces obtained from zkEVM do not contain the bytecode in the `output` section but a 0-padded address instead. This causes the traces to not be decoded properly in foundry causing issues in gas reporting and invariant tests.
Patch zkEVM `CREATE` call trace to populate it with the bytecode, for better interoperability with foundry.
Now:
```
Traces:
[32676] ZkTraceTest::testZkTraceOutputDuringCreate()
├─ [0] → new ConstructorAdder@0xF9E9ba9Ed9B96AB918c74B21dD0f1D5f2ac38a30
│   ├─ [127] → new Number@0xf232f12E115391c535FD519B00efADf042fc8Be5
│   │   └─ ← [Return] 2272 bytes of code
│   ├─ [85280] Number::five()
│   │   ├─ [91] → new InnerNumber@0xEd570f3F91621894E001DF0fB70BfbD123D3c8AD
│   │   │   └─ ← [Return] 736 bytes of code
│   │   ├─ [889] …
```

fix: patch create traces to work with foundry

---

crates/cheatcodes/src/inspector.rs
crates/evm/core/src/constants.rs
crates/evm/core/src/utils.rs
crates/forge/tests/fixtures/zk/Create2.s.sol
crates/forge/tests/it/zk/create2.rs
crates/forge/tests/it/zk/deploy.rs
crates/forge/tests/it/zk/mod.rs
crates/zksync/core/src/lib.rs
crates/zksync/core/src/vm/runner.rs

Using create2 in a script does not work as expected, as mentioned in this [issue](https://github.com/matter-labs/foundry-zksync/issues/570). Create2 was working for tests, but due to a check in the scripting process, we were unable to deploy it correctly in this case.
Adapt the script flow to use the create2Factory deployed in zksync

fix: Create2Factory on scripts

---

README.md

Incorporating the foundry book has led to updates in most sections of the readme. The main motivation for this cleanup is to maintain a single source of truth for documentation, present information in a straightforward manner, and provide useful links for quick access.
- Erase duplicated sections from the readme that are being explained in the book. 
- Sync communication with the one ZKsync is using to describe Foundry.
- Format & descriptions polishing

docs: readme cleanup 

---

crates/forge/bin/cmd/init.rs
crates/forge/bin/cmd/install.rs

https://github.com/Moonsong-Labs/forge-zksync-std was added to help with accessing our custom cheatcodes. But currently there's no way to `init` a forge project with these automatically.
Add `--zksync` flag to `forge init` that will automatically install `forge-zksync-std`.

feat: init forge project with zksync

---

Cargo.toml

- Was getting the below error when working with `--verify` 
```
Error:
Chain 300 not supported
```
Since https://github.com/alloy-rs/chains/pull/92 is now merged we can bump the dep so its now supported correctly. 
- bump to `alloy-chains = "0.1.33"`

chore: bump alloy-chains version so zksync-sepolia has correct chainID

---

crates/zksync/core/src/vm/inspect.rs

The gas usage value in `VmExecutionStatistics` is not representative of the actual gas a user pays which is observable when checking the values from the `RefundTracer`.
```
Gas Limit: 1073741824
Gas spent on computation: 260304
Gas spent on pubdata: 15827000
Pubdata published: 931
...
...
VmExecutionStatistics { gas_used: 25901, ... }
```
Utilize the `BootloaderDebugTracer` from era-test-node's modified `bootloader.yul` to utilize the gas usage parameters, to compute the accurate information.
```
Gas Limit: 1073741824
Gas spent on computation: 260304
Gas spent on pubdata: 15827000
Pubdata published: 931
...
BootloaderDebug { total_gas_limit_from_user: 1073741824, reserved_gas: 993741824, gas_per_pubdata: 17000, gas_limit_after_intrinsic: 79975930, gas_after_validation: 79906438, …
```

feat: add additional gas usage info from bootloader

---

crates/cheatcodes/src/inspector.rs
crates/script/src/runner.rs

The motivation of this PR is to solve the [issue 579](https://github.com/matter-labs/foundry-zksync/issues/579) that raised that a script that was meant to fail was not when not passing an rpc-url or fork-url
Check wether we are dealing with the test contract to avoid deploying it in Zk-vm and later try to execute in EVM.

fix: Add check in ZK create to check if it's the test contract

---

crates/cheatcodes/src/inspector.rs
crates/zksync/core/src/vm/inspect.rs

When vm is on zkVM mode, Calls/Creates on EVM are intercepted and run as transactions on the zkVM made by the caller of the test contract. There are currently two problems related to gas visibility for them: 
1.  `gas_used` value being returned is the computational gas spent by a bootloader program run on `OneTx` mode with that transaction on its heap. This includes the gas for general setup and transaction validation + execution. This value does not make sense in neither the case where we would want to interpret the intercepted call as a `CALL` opcode, because it would include setup + validation costs, nor for when we want to interpret it as an actual transaction (like done on evm tests when run on `isolate` mode), because it includes non transaction related gas and does not account for …

feat: return actual gas charged to the transaction caller for zkVM transactions

---

Cargo.lock
crates/zksync/core/src/vm/inspect.rs
crates/zksync/core/src/vm/mod.rs
crates/zksync/core/src/vm/runner.rs
crates/zksync/core/src/vm/tracers/cheatcode.rs
crates/zksync/core/src/vm/tracers/error.rs
crates/zksync/core/src/vm/tracers/mod.rs

Usually when a bootloader error occurs it simply panics without stating the reason.
Adds a custom tracer to print the internal bootloader error as done in https://github.com/matter-labs/era-test-node/pull/311

feat: add vm error tracer

---

Cargo.lock
crates/evm/traces/Cargo.toml
crates/evm/traces/src/decoder/mod.rs
crates/forge/src/gas_report.rs
crates/forge/tests/cli/cmd.rs
crates/forge/tests/it/test_helpers.rs
crates/zksync/compiler/src/lib.rs

Traces for intercepted creates in zkVM mode have evm bytecode on its input. The gas report uses that value to compute deployment size, which results in evm bytecode sizes being reported for zksync gas reports.
1. Add a `zk_contracts` field to the `CallTraceDecoder`, and use the artifact path to identify contracts that are in the zkVM.
2. When analyzing the node on the gas report use the trace output for computing the deployment size on those contracts.
The way the matching is implemented, if user sets a path with `zkout` as the solc artifact output, the contracts will be interpreted as zkevm and the output (deployed bytecode) will be used instead of the input. We could handle this edge case, but that clash would probably create problems elsewhere as well so, if we ever want to address it …

feat: use zk deployment sizes in gas report

---

crates/zksync/core/src/vm/inspect.rs

Even though why we need this has been lost in context, the `MAX_L1_GAS_PRICE_VALE` is being used as a min value in practice as  it is the argument of a `max` call. This would make sense in principle to ensure a non 0 gas price, but we would need to investigate further if this is actually needed.
Change the `MAX` semantics to `MIN` for the l1 gas price.

chore: change meaning of l1 one gas price constant

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/opts/build/zksync.rs
crates/forge/bin/cmd/create.rs
crates/zksync/core/src/lib.rs

Forge create didn't support the use of paymaster parameters to be able to use this zksync specific feature to deploy a contract. 
Introduce the ability to pass the paymaster address and input data in Forge create command
`zkforge create ./src/Counter.sol:Counter --rpc-url "https://sepolia.era.zksync.dev/" --private-key {PK} --zksync --zk-paymaster-address 0x3cB2b87D10Ac01736A65688F3e0Fb1b070B3eeA3 --zk-paymaster-input $(zkcast calldata "approvalBased(address,uint256,bytes)" 0x31c43ac5e6A0fe62954B9056441b0A214722516e 1000000000000000000 "0x")`
https://sepolia.explorer.zksync.io/tx/0xe57788a909df8bb4aae2265558ece52acd082328a46568d0d627db264d1ba039

feat: Paymaster support in Forge create

---

crates/forge/bin/main.rs

- Tired of manually deleting `zkout/` directory and cache 
- Adds support for running `forge clean` to zksync context
- Add zk_project.cleanup cmd to `forge clean`

feat: adds support for forge clean to remove zkout directory 

---

Cargo.lock
Cargo.toml
crates/forge/bin/cmd/create.rs
deny.toml

Testing out ledger support, the instruction used to sign EIP712 is not the correct one, but instead the generic one
The forked dependency ensures the right version of the command is used when signing EIP712 transactions
Uses https://github.com/Karrq/alloy/commit/64c230a235eb8d5eb78e39042525772008c8a3b8#diff-6011ef15e3cc46648c6b734f1fd9448bf40c3f8f23412282b84bb36e59ee9b56R47

fix: allow EIP712 signing for ledger

---

crates/zksync/core/src/vm/db.rs

* address issue with filtering create2 address factory 
* Causing failures 
Please ensure the following before submitting your PR:

fix: address issue with filtering create2 address factory 

---

crates/evm/core/src/utils.rs
crates/verify/src/zk_provider.rs
crates/zksync/core/src/utils.rs
crates/zksync/core/src/vm/inspect.rs

* Turns on evm_interpreter 
* Fixes gas issues
**Note:** Some improvements can still be made, for instance we return `Error function_selector = 0xe8d529f9, data = 0xe8d529f9` as a String and its never decoded via Openchain. We should improve this to do so, then its human readable as `OrderFailed()` instead of `0xe8d529f9`.
* By specifying true for base system contracts for evm interpreter we can successfully replay both EraVM and EVM transactions during replay
* The gas calculation has not been updated for quite some time resulting in incorrect gas limits 
**BEFORE:**
```
cast run --zksync --rpc-url https://api.mainnet.abs.xyz …
```

fix: address issue with replaying tx via cast run 

---

crates/strategy/zksync/src/cheatcode/runner/mod.rs
testdata/zk/StateDiff.t.sol

* Updates `zksync_remove_duplicate_account_access` to use the most recent stack entry and check bounds before removal, logging a warning if the index is out of range
* Closes #1064 
Please ensure the following before submitting your PR:

fix: addresses issue with state diff recording idx
