matter-labs/foundry-zksync

README.md, cli/src/cmd/cast/zk_send.rs
Added troubleshooting section to README & updated error handling for txn
=> Added troubleshooting section to README & updated error handling for txn

cli/src/cmd/forge/zk_create.rs
Added better error messages when file or contract name is not correct
=> Added better error messages when file or contract name is not correct

README.md, cli/src/cmd/forge/zk_build.rs, cli/src/cmd/forge/zksolc_manager.rs
Added support for Macs with Apple Silicon:
- selecting proper zksync compiler
- information on where to get the most recent solidity
=> Added support for Macs with Apple Silicon

config/src/lib.rs
Removing the unnecessary config option that was breaking tests.
=> fix test compilation issue

Cargo.lock
There was an upgrade of zksync code - so switched to use the new version.
=> Fixed compilation issue

README.md
The --is-system flag in the readme was broke
Unindented the tag
=> fix(readme): --is-system flag image

.github/workflows/test.yml
* Upgrades the runner for `forge fmt`
* We kept hitting OOM issue
=> chore: update runner for forge fmt

.github/workflows/test.yml
* Runs smoke test on PRs
* To detect regressions
Test passes
=> feat: run smoke test on PRs

crates/common/src/zksolc_manager.rs, crates/zkforge/bin/cmd/test/mod.rs
* Uses `zksolc_manager` during `execute_test` 
* Updates error messages
* If zksolc compiler is not downloaded test command would previously panic. Now it will download and then compile.
* Improves error messages.
=> fix: makes use of `zksolc_manager` during test cmd to download compiler if not present

.github/workflows/test.yml, .gitmodules, crates/era-cheatcodes/tests/test.sh
* Enable cheatcode tests
* Carry-over from era-revm
CI passes on cheatcode tests
=> feat: enable cheatcode tests

crates/era-cheatcodes/tests/test.sh
Fix downloading compiler for mac
Current script doesn't work for mac os
=> fix(test): Download  correct compiler for mac

crates/common/src/zk_compile.rs
* handles compiler errors for improved readability  
* separates warning and error handling 
* Couldn't read error messages previously  
**BEFORE**
**AFTER**
=> fix: improves error handling and readability 

Cargo.lock, crates/common/src/zk_compile.rs, crates/evm/core/src/era_revm/transactions.rs, crates/evm/evm/src/executors/mod.rs, crates/evm/fuzz/src/strategies/invariants.rs, crates/zkforge/Cargo.toml, crates/zkforge/bin/cmd/test/mod.rs, crates/zkforge/src/multi_runner.rs, crates/zkforge/src/runner.rs, smoke-test/foundry.toml, smoke-test/src/Counter.sol, smoke-test/src/foundry.toml, smoke-test/test.sh
* Add support for invariant testing
* Achieve feature parity
Smoke test passes
=> feat: add support for invariant testing

crates/era-cheatcodes/src/cheatcodes.rs, crates/era-cheatcodes/tests/src/cheatcodes/RollFork.t.sol
* Adds rollFork cheatcode
* To support foundry for zksync
-
=> feat: add roll fork cheatcode

crates/zkforge/bin/cmd/script/build.rs, crates/zkforge/bin/cmd/zk_build.rs
* update compiler setup to account for zksolc settings and consistent with test / build cmds
* script compile process was not picking up on configurations
=> fix: update compiler setup to account for zksolc settings and consistent with test / build cmds

.github/workflows/release.yml
* Updates release pipeline to be consistent with ETN
* Previous release pipeline was tailored to upstream needs and did not account for zkforge / zkcast 
* Keep it consistent with ETN for easy maintainability  
=> chore: update release pipeline for zkforge and zkcast releases

crates/common/src/zksolc_manager.rs
* chore: adds zksolc 1.3.22
* Keep up with the latest compiler
=> chore: adds zksolc 1.3.22

README.md
* Adds explicit rust installation instructions
* Some peoples builds were failing due to not having proper toolchain installed
=> chore: add explicit rust installation instructions to readme

.github/workflows/test.yml, crates/common/src/zksolc_manager.rs
* update zksolc to latest `1.3.23`
*  update zksolc to latest `1.3.23` to support more solc versions
=> chore: update zksolc to latest `1.3.23`

crates/common/src/zk_compile.rs, crates/config/src/zksolc_config.rs, crates/zkforge/Cargo.toml, crates/zkforge/bin/cmd/script/build.rs, crates/zkforge/bin/cmd/test/mod.rs, crates/zkforge/bin/cmd/zk_build.rs
* Replicate @nbaztec work for the compiler flags
* Resolves the issue comparing filenames to know if should_compile or not when working with binary in another repo
=> fix: flags for compiling with globset

crates/era-cheatcodes/src/cheatcodes.rs, crates/era-cheatcodes/tests/src/cheatcodes/Prank.t.sol, crates/era-cheatcodes/tests/src/cheatcodes/StartPrank.t.sol
* Add support for `prank`
* Fix pranking nested calls
* Foundry feature parity
=> feat: prank cheatcode

crates/common/src/zksolc_manager.rs
* Add fetching of recommended minimal `zsksolc` version as mentioned in #96 
* Add check for version passed through `--use-zksolc` parameter that it's greater than minimal
* Add an ability to skip this check using `ZKSOLC_SKIP_MINIMAL_VERSION_CHECK`
* Closes: #96
=> feat: add check of minimal recommended zksolc version

crates/forge/bin/cmd/create.rs, crates/forge/src/runner.rs
Redundant debug print statements are unwanted.
Removes print statements.
=> chore: remove prints

Cargo.lock, crates/zksync/compiler/Cargo.toml, crates/zksync/compiler/src/zksolc/config.rs, zk-tests/test.sh
* CI tests don't work as the async executor deadlocks indefinitely
* Detect and handle sync and async contexts properly
=> fix: make ci work

crates/forge/bin/cmd/create.rs, zk-tests/test.sh
=> feat: add manual factory deps

.github/workflows/aave-delivery-infrastructure.yml
=> feat: Add Aave delivery infrastructure testing in CI

foundryup/README.md, foundryup/foundryup, foundryup/install
- Updates install and foundryup scripts to reflect foundry-zksync, these will not work until merged on `dev` branch although you can test by pulling the branch locally and updating the `BIN_URL` to point to this branch on GitHub. 
- These will be used for curl link installation
=> feat: update install and foundryup scripts to reflect foundry-zksync

crates/zksync/core/src/vm/farcall.rs, crates/zksync/core/src/vm/runner.rs, crates/zksync/core/src/vm/tracer.rs, zk-tests/src/Ownership.t.sol
DelegateCall does not currently apply correct values.
Override `address(this)` during delegate calls.
=> feat: support delegateCall

.github/workflows/infrastructure.yml
- Renames workflow accordingly 
- Updates build command for faster builds as we do not need the other binaries for this workflow
=> chore: update workflow for test regression check

crates/zksync/compiler/src/zksolc/manager.rs
- Adds support for zksolc 1.4.1
- This will provide support to latest solc version in zksolc, although we still need to update foundry-compilers for 0.8.25 support. See: #341
=> feat: adds support for zksolc 1.4.1

.github/workflows/release.yml
- Currently releases are automated nightly, this allows releases to be tagged with commit hash and listing the applicable changes.
-
=> chore: remove the draft field for regular pre-releases

zk-tests/src/Maths.sol, zk-tests/src/MissingLibraries.sol, zk-tests/src/NestedMaths.sol, zk-tests/src/NestedMissingLibraries.sol, zk-tests/test.sh
After #357 and #367 we still lack a test case to cover the features in CI
Add 2 scripts that use libraries, change the test procedure to make use of the new features
Other branches:
=> test: add case for contracts w/ libraries

Cargo.lock
Contains zksync's solc version bump
=> chore: update foundry-compilers

crates/zksync/core/src/vm/farcall.rs
=> fix to support instant return

README.md
Closes #431 
Update the links to the new page
=> docs: update zksync links

README.md, crates/config/README.md, crates/config/src/lib.rs
With #430 merged, zksync-specific configuration has changed, and documentation has become oudated.
Update documentation with examples showing how to use the new configuration system.
The PR also restores the ability to specify profile-specific zksync configuration.
=> docs: zksync config

Cargo.lock, crates/common/src/compile.rs, crates/forge/bin/cmd/build.rs, crates/forge/bin/cmd/test/mod.rs, crates/script/src/build.rs, crates/zksync/compiler/Cargo.toml, crates/zksync/compiler/src/lib.rs
Fix zksolc build on `foundry-update-4af6cfa`
=> fix: zksolc build [upstream-merge]

Cargo.lock, crates/cheatcodes/src/inspector.rs, crates/common/src/compile.rs, crates/evm/evm/src/inspectors/stack.rs, crates/script/src/build.rs, crates/zksync/compiler/src/lib.rs, crates/zksync/compiler/src/zksolc/mod.rs, zk-tests/foundry.toml
Fixes a `step_end` regression that was using the incorrect state.
This should _potentially_ make the other tests pass fine.
=> fix: forge test

.github/workflows/release.yml
Nightly job is broken due to invalid config
=> fix: nightly release job

README.md
Clarify the current limitations regarding Windows support to prevent confusion for users who might expect compatibility, especially those transitioning from Foundry.
Add a clear reference to platform limitations at the top of the README file as well as explicitly stating that Windows is not supported in the dedicated section to ensure it is easily accessible and visible to users.
=> docs: windows compatibility clarification

.github/workflows/deny.yml, .github/workflows/infrastructure.yml, .github/workflows/test.yml
We used to have the workflows pointing to dev
Now that dev got rename to main this adjust the workflows to run in the PRs
=> fix: Change branch from workflows to main

crates/forge/tests/it/zk/mod.rs, crates/forge/tests/it/zk/ownership.rs, testdata/zk/Ownership.t.sol
Migrate test suite to cargo test
Added `Ownership.t.sol` test to cargo test
=> test(zk): Migrate ownership zksync tests to cargo test

crates/forge/tests/it/zk/cheats.rs, testdata/zk/ZkForcedRet.t.sol
This single-purpose test is ran only in zk-tests
Migrate to forge suite
=> test(zk): migrate forced return

Cargo.toml
Speed up zkVM usage in debug builds
=> perf(dev): compile optimized multivm crate

Cargo.lock, Cargo.toml, crates/test-utils/src/zksync.rs, crates/zksync/core/src/vm/inspect.rs, crates/zksync/core/src/vm/runner.rs
=> chore: update zksync deps

crates/config/README.md
=> fix(docs): typo for `enable_eravm_extensions`

Cargo.lock
Brings in https://github.com/alloy-rs/chains/pull/78
Fixes https://github.com/matter-labs/foundry-zksync/issues/508
=> chore: update alloy-chains to 0.1.27

crates/forge/tests/it/test_helpers.rs, crates/zksync/compiler/src/lib.rs
Use latest version of Zksolc by deafult
=> chore: Update zksolc to 1.5.2

crates/forge/tests/it/zk/create.rs, crates/forge/tests/it/zk/mod.rs, testdata/zk/ERC20.sol, testdata/zk/TokenReceiver.sol
We use zk-tests to run forge create tests
Migrated both the ERC20 and TokenReceiver contracts to /testdata and added tests for their deployments.
=> test: Migrate forge create tests to cargo

crates/forge/tests/it/test_helpers.rs, crates/zksync/compiler/src/lib.rs
Update zksolc default version to the latest (1.5.3)
=> chore: Update zksolc to 1.5.3

crates/forge/tests/fixtures/zk/Deploy.s.sol, crates/forge/tests/it/zk/deploy.rs, crates/forge/tests/it/zk/mod.rs
Migrate double deployment test from zk-test
=> test: Added testing of multiple deploy of same contract

Cargo.lock
Update foundry-compilers with changes introduced in: https://github.com/Moonsong-Labs/compilers/pull/29. This should download arm binaries for machines where the arm architecture is detected.
=> feat: update foundry-compilers

install-foundry-zksync
- Addresses failed CI job on main for testing installation script https://github.com/matter-labs/foundry-zksync/actions/runs/10801412610/job/29961516115
- Downloading from github url and making executable, removing install artifacts
=> fix: ci for testing installation script and remove artifacts

README.md
- Updates readme to include link to foundry zksync book
- Removes unnecessary README info about inner workings which is more relevant for foundry zksync book
=> chore: adds link to book and reorg

.github/workflows/bump-forge-std.yml
`forge-std ` should be updated for testdata either manually or via upstream sync to avoid being out of sync with our latest upstream commits.
Disable `bump-forge-std` action.
=> chore: disable bump-forge-std action

Cargo.lock
https://github.com/matter-labs/foundry-zksync/pull/589 updated `alloy-chains` but the change was not impacted in the `Cargo.lock` file.
Update `Cargo.lock` file
=> chore: update Cargo.lock with new alloy-chains version

Cargo.lock, crates/common/src/compile.rs, crates/verify/src/etherscan/flatten.rs, crates/verify/src/zk_provider.rs, crates/zksync/compiler/src/lib.rs
https://github.com/Moonsong-Labs/compilers/pull/30 adds api changes to detect ZKsync solc being used.
Integrate api changes and add a test to ensure zksync solc is used when a specific version is required
=> feat: use new compilers api and add zkync solc test

.github/CODEOWNERS
* Adds MSL team to CODEOWNERS
* Reviews
=> chore: add msl team to CODEOWNERS

crates/forge/src/cmd/doc/server.rs
Upstream fix for forge doc --serve
Use fallback service instead of nesting
=> fix(doc): update router to use fallback_service for better 404 handling
